# FROM node:20.18.0-slim AS base
FROM node:18-alpine AS base

ARG PORT=3101
WORKDIR /src

# Build
FROM base AS build
COPY --link package.json package-lock.json .
RUN npm install
COPY --link . .
RUN npm run build

# Run
FROM base
ENV PORT=$PORT
ENV NODE_ENV=production
ENV MONGO_CONNECTION_STRING=mongodb+srv://doadmin:T047v2J9G1CVP8j3@pepeat-mongo-db-ac667bc3.mongo.ondigitalocean.com/pepeat?tls=true&authSource=admin&replicaSet=pepeat-mongo-db

# COPY --from=build /src/node_modules ./node_modules
# COPY --from=build /src/dist ./dist
# COPY --from=build /src/package.json ./package.json
COPY --from=build /src /src

EXPOSE $PORT

CMD [ "node", "index.js"]

# FROM node:14-alpine

# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

# WORKDIR /home/node/app

# COPY package*.json ./

# USER node

# RUN npm install

# COPY --chown=node:node . .

# ARG PORT=3101
# EXPOSE $PORT

# CMD [ "node", "index.js" ]